version: "2"
services:
  web:
    build: .
    ports:
      - 80:80
      - 8000:8000
    volumes:
      - ./biosecurity_management:/app/biosecurity_management
    env_file:
      - development.env
    networks:
      - net
networks:
  net: